[env:seeed_xiao_rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
lib_deps =
  olikraus/U8g2@^2.36.9
build_flags =
  -DDEBUG
  -DDEBUG_FAKE_BPM=60
