[env:seeed_xiao_rp2040]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
board = seeed-xiao-rp2040
framework = arduino
src_dir = src
lib_deps =
  SdFat
  adafruit/Adafruit WavePlayer Library@^1.0.7


